### ISSUE TITLE
Dead Link: Interview with the creator of NginX

### ISSUE THREAD

**Issue by DarkSuniuM** [fcambus/nginx-resources#17]
The link to "Interview ith the creator of NginX from Minded.com is dead
Here is the link to archive
https://web.archive.org/web/20180614224054/http://mindend.com/interview-with-the-creator-of-nginx/

**Comment by fcambus** [comment]
Thanks for reporting the issue.

Interestingly, the content is still up on https://mindend.com/interview-with-the-creator-of-nginx/ but the certificate is expired.

**Comment by fcambus** [comment]
Sent a mail to the author, will act on this issue once I get an update.

**Comment by DarkSuniuM** [comment]
> Thanks for reporting the issue.
> 
> Interestingly, the content is still up on https://mindend.com/interview-with-the-creator-of-nginx/ but the certificate is expired.

I by saying link is dead didn't mean anything is wrong with certification :D at that time it was giving me 502 response code :D

**Comment by DarkSuniuM** [comment]
> > Thanks for reporting the issue.
> > Interestingly, the content is still up on https://mindend.com/interview-with-the-creator-of-nginx/ but the certificate is expired.
> 
> I by saying link is dead didn't mean anything is wrong with certification :D at that time it was giving me 502 response code :D

Oh seems like http version of the link still returns 502

**Comment by fcambus** [comment]
Haven't heard back and site is still down, so moved link to archive.org in 2aa7e8d4b287be2f4f08473f6dab7e866ee1f572.

Thanks.
