### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [fcambus/nginx-resources#23]
Hi, I found broken hyperlinks:

- [ ] https://www.airpair.com/nginx/extending-nginx-tutorial (file: README.md, status code: 503)
- [ ] http://rny.io/nginx/postgresql/2013/07/26/simple-api-with-nginx-and-postgresql.html (file: README.md, error: EAI_AGAIN)
- [ ] https://tech.3scale.net/2013/01/09/augment-your-api-without-touching-it (file: README.md, status code: 404)
- [ ] https://blog.dutchcoders.io/openresty-with-dynamic-generated-certificates/ (file: README.md, error: ENOTFOUND)

**Comment by fcambus** [comment]
Fixed in d871404e090a087a12b943e2bd65595a076028e0, thanks for your report!
