### ISSUE TITLE
Nginx in Docker

### ISSUE THREAD

**Issue by jhagege** [fcambus/nginx-resources#8]
Any good ressources for Nginx in Docker ?
Thanks

**Comment by retrohacker** [comment]
The official image has some great patterns for using Nginx in Docker: https://hub.docker.com/_/nginx/

Useful to mimic even if you are rolling your own. The closed issues are useful for understanding why some of the decisions were made: https://github.com/nginxinc/docker-nginx/issues

**Comment by jhagege** [comment]
Thanks for fast answer ! 
Would be great to add it to the list of ressources :-)
#9

**Comment by fcambus** [comment]
Closing this, see #9 for feedback.
